 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyek_michiko_creative;

import koneksi.Koneksi;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author wafiq
 */
public class Fitur_Suplier extends javax.swing.JFrame {
private Connection conn;

    public Fitur_Suplier() {
        initComponents();
       conn = Koneksi.getConnection();
       getData();
    }
     private void getData() {
    DefaultTableModel model = (DefaultTableModel) jtabell.getModel();
    model.setRowCount(0); 

    try { 
        String sql = "SELECT * FROM suplier"; 
        PreparedStatement st = conn.prepareStatement(sql); 
        ResultSet rs = st.executeQuery();

        while (rs.next()) { 
            String id_suplier = rs.getString("id_suplier");  
            String nama_suplier = rs.getString("Nama_Suplier");
            String no_telp = rs.getString("no_telp");
            String alamat = rs.getString("alamat_suplier");

            
            Object[] rowData = {id_suplier, nama_suplier, no_telp, alamat}; 
            model.addRow(rowData);
        }

        
        rs.close(); 
        st.close();
    } 
    catch (Exception e) { 
        Logger.getLogger(Fitur_Suplier.class.getName()).log(Level.SEVERE, null, e); 
        JOptionPane.showMessageDialog(this, "Error saat menambahkan data: " + e.getMessage());
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtabell = new javax.swing.JTable();
        jmasuk = new javax.swing.JButton();
        jhapus = new javax.swing.JButton();
        jedit = new javax.swing.JButton();
        tid_suplier = new javax.swing.JTextField();
        tnama_suplier = new javax.swing.JTextField();
        tno_tlp = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jberanda = new javax.swing.JButton();
        jbarang = new javax.swing.JButton();
        jpenjualan = new javax.swing.JButton();
        jpembelian = new javax.swing.JButton();
        jsuplier = new javax.swing.JButton();
        jlaporan = new javax.swing.JButton();
        jkeluar = new javax.swing.JButton();
        jcari = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtabell.setBackground(new java.awt.Color(255, 204, 102));
        jtabell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID SUPLIER", "NAMA SUPLIER", "N0 TLP", "ALAMAT SUPLIER"
            }
        ));
        jtabell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabellMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabell);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 850, 270));

        jmasuk.setBackground(new java.awt.Color(255, 204, 51));
        jmasuk.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jmasuk.setText("Tambah");
        jmasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmasukActionPerformed(evt);
            }
        });
        getContentPane().add(jmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 100, 30));

        jhapus.setBackground(new java.awt.Color(255, 204, 51));
        jhapus.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jhapus.setText("Hapus");
        jhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 90, 30));

        jedit.setBackground(new java.awt.Color(255, 204, 51));
        jedit.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jedit.setText("Ubah");
        jedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditActionPerformed(evt);
            }
        });
        getContentPane().add(jedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 90, 30));

        tid_suplier.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        tid_suplier.setBorder(null);
        tid_suplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tid_suplierActionPerformed(evt);
            }
        });
        getContentPane().add(tid_suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 210, 30));

        tnama_suplier.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        tnama_suplier.setBorder(null);
        tnama_suplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnama_suplierActionPerformed(evt);
            }
        });
        getContentPane().add(tnama_suplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 232, 210, 30));

        tno_tlp.setBackground(new java.awt.Color(0, 0, 0, 0));
        tno_tlp.setBorder(null);
        tno_tlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tno_tlpActionPerformed(evt);
            }
        });
        getContentPane().add(tno_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 210, 30));

        talamat.setBackground(new java.awt.Color(0, 0, 0, 0));
        talamat.setBorder(null);
        talamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talamatActionPerformed(evt);
            }
        });
        getContentPane().add(talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 210, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 70, 60));

        jberanda.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jberanda.setBorder(null);
        jberanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jberanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jberandaActionPerformed(evt);
            }
        });
        getContentPane().add(jberanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 110, 40));

        jbarang.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbarang.setBorder(null);
        jbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarangActionPerformed(evt);
            }
        });
        getContentPane().add(jbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 140, 30));

        jpenjualan.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jpenjualan.setBorder(null);
        jpenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpenjualanActionPerformed(evt);
            }
        });
        getContentPane().add(jpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 180, 30));

        jpembelian.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jpembelian.setBorder(null);
        jpembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpembelianActionPerformed(evt);
            }
        });
        getContentPane().add(jpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, 180, 30));

        jsuplier.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jsuplier.setBorder(null);
        jsuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsuplierActionPerformed(evt);
            }
        });
        getContentPane().add(jsuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 230, 40));

        jlaporan.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jlaporan.setBorder(null);
        jlaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 490, 160, 40));

        jkeluar.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jkeluar.setBorder(null);
        jkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 750, 140, 40));

        jcari.setBackground(new java.awt.Color(0, 0, 0, 0));
        jcari.setBorder(null);
        jcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcariActionPerformed(evt);
            }
        });
        getContentPane().add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 40, 40));

        tcari.setBackground(new java.awt.Color(0, 0, 0, 0));
        tcari.setBorder(null);
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 220, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fitur data suplier sayang.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tnama_suplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnama_suplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnama_suplierActionPerformed

    private void tno_tlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tno_tlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tno_tlpActionPerformed

    private void talamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talamatActionPerformed

    private void jeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditActionPerformed
        // TODO add your handling code here:
        int selectedRow= jtabell.getSelectedRow();
            if(selectedRow == -1){
                JOptionPane.showMessageDialog(this,"Pilih tabel yang akan di ubah");
                return;
        }
    String id_suplier = jtabell.getValueAt(selectedRow, 0).toString();
    String nama_suplier = tnama_suplier.getText();
    String no_telp = tno_tlp.getText();
    String alamat = talamat.getText();
//    String username = "bayu";
    
    
    if (id_suplier.isEmpty() || nama_suplier.isEmpty() || no_telp.isEmpty() || alamat.isEmpty() ) { 
        JOptionPane.showMessageDialog(this, "Harap lengkapi semua field sebelum menambahkan data."); 
        return;
    }
    
    try {
        String sql = "UPDATE suplier SET Nama_Suplier = ?, no_telp = ?, alamat_suplier = ? WHERE id_suplier = ?";
        PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, nama_suplier);
            st.setString(2, no_telp);
            st.setString(3, alamat);
            st.setString(4, id_suplier);
//            st.setString(5, username);
        int rowsUpdated = st.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
            getData(); 
            resetForm(); 
        }

        st.close();
    } catch (Exception e) {
        Logger.getLogger(Fitur_Suplier.class.getName()).log(Level.SEVERE, null, e);
        JOptionPane.showMessageDialog(this, "Error saat mengubah data: " + e.getMessage());
    }     
    }//GEN-LAST:event_jeditActionPerformed

    private void jmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmasukActionPerformed
        // TODO add your handling code here:
String id_suplier = tid_suplier.getText();
String nama_suplier = tnama_suplier.getText();
String no_telp = tno_tlp.getText();
String alamat = talamat.getText();
String username = "bayu";

if (id_suplier.isEmpty() || nama_suplier.isEmpty() || no_telp.isEmpty() || alamat.isEmpty() ) {
    JOptionPane.showMessageDialog(this, "Harap lengkapi semua field sebelum menambahkan data.");
    return;
}

try {
    String sql = "INSERT INTO suplier (id_suplier, Nama_Suplier, no_telp, alamat_suplier, username) VALUES (?, ?, ?, ?, ?)";
    PreparedStatement st = conn.prepareStatement(sql);
    st.setString(1, id_suplier);
    st.setString(2, nama_suplier);
    st.setString(3, no_telp);
    st.setString(4, alamat);
    st.setString(5, username);
    
    int rowInserted = st.executeUpdate();
    if (rowInserted > 0) {
        JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
        resetForm(); 
        getData(); 
    }

    st.close();
} catch (Exception e) {
    Logger.getLogger(Fitur_Suplier.class.getName()).log(Level.SEVERE, null, e);
    JOptionPane.showMessageDialog(this, "Error saat menambahkan data: " + e.getMessage());
}

      

    }//GEN-LAST:event_jmasukActionPerformed

    private void jtabellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabellMouseClicked
        // TODO add your handling code here:
   int selectedRow = jtabell.getSelectedRow();
if (selectedRow == -1) {
    JOptionPane.showMessageDialog(this, "Pilih tabel yang akan diubah");
    return;
}

    String id_suplier = jtabell.getValueAt(selectedRow, 0).toString();
    String nama_suplier = jtabell.getValueAt(selectedRow, 1).toString();
    String no_telp = jtabell.getValueAt(selectedRow, 2).toString();           
    String alamat = jtabell.getValueAt(selectedRow, 3).toString();
// String username = jtabell.getValueAt(selectedRow, 4).toString();

    tid_suplier.setText(id_suplier);
    tnama_suplier.setText(nama_suplier);
    tno_tlp.setText(no_telp);          
    talamat.setText(alamat);
// tusername.setText(username);

    }//GEN-LAST:event_jtabellMouseClicked

    private void jhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhapusActionPerformed
        // TODO add your handling code here:
    int selectedRow = jtabell.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih tabel yang akan dihapus");
        return;
    }

    String id_suplier = jtabell.getValueAt(selectedRow, 0).toString();
    
    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus item ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            String sql = "DELETE FROM suplier WHERE id_suplier = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, id_suplier);
            int rowsDeleted = st.executeUpdate();
            
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                getData(); // Memperbarui data yang ada di tabel
                resetForm(); // Mengosongkan form input
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau gagal dihapus.");
            }
            
            st.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_jhapusActionPerformed

    private void jberandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jberandaActionPerformed
        // TODO add your handling code here:
        MenuFitur menu = new MenuFitur();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jberandaActionPerformed

    private void jbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarangActionPerformed
        // TODO add your handling code here:
        Fitur_Barang barang = new Fitur_Barang();
        barang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbarangActionPerformed

    private void jlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaporanActionPerformed
        // TODO add your handling code here:
         Laporan_Pemasukan laporan = new Laporan_Pemasukan();
        laporan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlaporanActionPerformed

    private void jpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpenjualanActionPerformed
        // TODO add your handling code here:
        Fitur_TransaksiJual suplier = new Fitur_TransaksiJual();
        suplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jpenjualanActionPerformed

    private void jsuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsuplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsuplierActionPerformed

    private void jpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpembelianActionPerformed
        // TODO add your handling code here:
        Fitur_TransaksiBeli pembelian = new Fitur_TransaksiBeli();
        pembelian.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jpembelianActionPerformed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void jcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcariActionPerformed
        // TODO add your handling code here:
         String keyword = tcari.getText().trim(); 
    if (!keyword.isEmpty()) {
        searchData(keyword); 
    } else {
        getData(); 
    }
}

private void searchData(String keyword) {
    DefaultTableModel model = (DefaultTableModel) jtabell.getModel();
    model.setRowCount(0); 

    String sql = "SELECT * FROM suplier WHERE id_suplier LIKE ? OR Nama_Suplier LIKE ?";
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, "%" + keyword + "%");
        stmt.setString(2, "%" + keyword + "%");

        try (ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                String id_suplier = rs.getString("id_suplier");
                String nama_suplier = rs.getString("Nama_Suplier");
                String alamat = rs.getString("alamat_suplier");
                String notlp = rs.getString("no_telp");
                String username = rs.getString("username");
               
                Object[] rowData = {
                   id_suplier,nama_suplier,alamat,notlp
                };
                model.addRow(rowData);
            }
        }
    } catch (Exception e) {
        Logger.getLogger(Fitur_Suplier.class.getName()).log(Level.SEVERE, "Error saat mencari data", e);
        JOptionPane.showMessageDialog(this, 
            "Error saat mencari data: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jcariActionPerformed

    private void jkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkeluarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
        System.exit(0); 
    } else {
    }
    }//GEN-LAST:event_jkeluarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuFitur fitur = new MenuFitur();
        fitur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tid_suplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tid_suplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tid_suplierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fitur_Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fitur_Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fitur_Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fitur_Suplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fitur_Suplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbarang;
    private javax.swing.JButton jberanda;
    private javax.swing.JButton jcari;
    private javax.swing.JButton jedit;
    private javax.swing.JButton jhapus;
    private javax.swing.JButton jkeluar;
    private javax.swing.JButton jlaporan;
    private javax.swing.JButton jmasuk;
    private javax.swing.JButton jpembelian;
    private javax.swing.JButton jpenjualan;
    private javax.swing.JButton jsuplier;
    private javax.swing.JTable jtabell;
    private javax.swing.JTextField talamat;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tid_suplier;
    private javax.swing.JTextField tnama_suplier;
    private javax.swing.JTextField tno_tlp;
    // End of variables declaration//GEN-END:variables
 
    private void resetForm() {
        tid_suplier.setText("");
        tnama_suplier.setText("");
        tno_tlp.setText("");
        talamat.setText("");
        
      
    }
}
