/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyek_michiko_creative;


import java.math.BigDecimal;
import koneksi.Koneksi;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.sql.SQLException;

public class Fitur_TransaksiBeli extends javax.swing.JFrame {
private Connection conn;
    /**
     * Creates new form Fitur_TransaksiBeli
     */
    public Fitur_TransaksiBeli() {
        initComponents();
        conn = Koneksi.getConnection();
        getData();
    } 
    private void getData() {
    DefaultTableModel model = (DefaultTableModel) jtabeltransaksibeli.getModel();
    model.setRowCount(0); 
    String sql = "SELECT * FROM Transaksi_beli";

   
    try (PreparedStatement st = conn.prepareStatement(sql);
         ResultSet rs = st.executeQuery()) {
        
       
        while (rs.next()) {
            String idtransaksi = rs.getString("id_transaksi_beli");
            String idsuplier = rs.getString("id_suplier");
            String namabarang = rs.getString("Nama_barang");
            String jumlah = rs.getString("jumlah");
            String tanggal = rs.getString("tanggal");
            
           
            BigDecimal totalharga = rs.getBigDecimal("total_harga");
            String idbarang = rs.getString("id_barang");
            String username = rs.getString("username");

            
            Object[] rowData = {idtransaksi, idsuplier, namabarang, jumlah, tanggal, totalharga, idbarang, username};
            model.addRow(rowData);
        }
    } catch (Exception e) {
        
        Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(Level.SEVERE, null, e);
        JOptionPane.showMessageDialog(this, "Error saat menambahkan data: " + e.getMessage());
    }
}

 

//    Transaksi transaksi = new Transaksi(); 
//    transaksi.beliBarang("1", 10); 




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtambah = new javax.swing.JButton();
        tidtransaksi = new javax.swing.JTextField();
        tidsuplier = new javax.swing.JTextField();
        tnamabarang = new javax.swing.JTextField();
        tjumlah = new javax.swing.JTextField();
        ttanggal = new javax.swing.JTextField();
        ttotalharga = new javax.swing.JTextField();
        tusername = new javax.swing.JTextField();
        tidbarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabeltransaksibeli = new javax.swing.JTable();
        jubah = new javax.swing.JButton();
        jhapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jberanda = new javax.swing.JButton();
        jbarang = new javax.swing.JButton();
        jpenjualan = new javax.swing.JButton();
        jpembelian = new javax.swing.JButton();
        jsuplier = new javax.swing.JButton();
        jkeluar = new javax.swing.JButton();
        jlaporan = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        jcari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtambah.setBackground(new java.awt.Color(255, 204, 51));
        jtambah.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jtambah.setText("tambah");
        jtambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 90, 30));

        tidtransaksi.setBackground(new java.awt.Color(0, 0, 0, 0));
        tidtransaksi.setBorder(null);
        getContentPane().add(tidtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 210, 30));

        tidsuplier.setBackground(new java.awt.Color(0, 0, 0, 0));
        tidsuplier.setBorder(null);
        getContentPane().add(tidsuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 232, 220, 30));

        tnamabarang.setBackground(new java.awt.Color(0, 0, 0, 0));
        tnamabarang.setBorder(null);
        tnamabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamabarangActionPerformed(evt);
            }
        });
        getContentPane().add(tnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 312, 220, 30));

        tjumlah.setBackground(new java.awt.Color(0, 0, 0, 0));
        tjumlah.setBorder(null);
        tjumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjumlahActionPerformed(evt);
            }
        });
        getContentPane().add(tjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 392, 220, 30));

        ttanggal.setBackground(new java.awt.Color(0, 0, 0, 0));
        ttanggal.setBorder(null);
        getContentPane().add(ttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 152, 220, 30));

        ttotalharga.setBackground(new java.awt.Color(0, 0, 0, 0));
        ttotalharga.setBorder(null);
        getContentPane().add(ttotalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 232, 220, 30));

        tusername.setBackground(new java.awt.Color(0, 0, 0, 0));
        tusername.setBorder(null);
        getContentPane().add(tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 220, 30));

        tidbarang.setBackground(new java.awt.Color(0, 0, 0, 0));
        tidbarang.setBorder(null);
        tidbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidbarangActionPerformed(evt);
            }
        });
        getContentPane().add(tidbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 312, 220, 30));

        jtabeltransaksibeli.setBackground(new java.awt.Color(255, 204, 102));
        jtabeltransaksibeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id transaksi beli", "Id suplier", "Nama barang", "Jumlah", "Tanggal", "Total harga", "Id barang", "Penjual"
            }
        ));
        jtabeltransaksibeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabeltransaksibeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabeltransaksibeli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 850, 270));

        jubah.setBackground(new java.awt.Color(255, 204, 51));
        jubah.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jubah.setText("ubah");
        jubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jubahActionPerformed(evt);
            }
        });
        getContentPane().add(jubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 90, 30));

        jhapus.setBackground(new java.awt.Color(255, 204, 51));
        jhapus.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jhapus.setText("hapus");
        jhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 90, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 30, 80, 50));

        jberanda.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jberanda.setBorder(null);
        jberanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jberanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jberandaActionPerformed(evt);
            }
        });
        getContentPane().add(jberanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 120, 40));

        jbarang.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbarang.setBorder(null);
        jbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbarangActionPerformed(evt);
            }
        });
        getContentPane().add(jbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 140, 30));

        jpenjualan.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jpenjualan.setBorder(null);
        jpenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpenjualanActionPerformed(evt);
            }
        });
        getContentPane().add(jpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 180, 30));

        jpembelian.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jpembelian.setBorder(null);
        jpembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpembelianActionPerformed(evt);
            }
        });
        getContentPane().add(jpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, 180, 30));

        jsuplier.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jsuplier.setBorder(null);
        jsuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jsuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsuplierActionPerformed(evt);
            }
        });
        getContentPane().add(jsuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 220, 30));

        jkeluar.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jkeluar.setBorder(null);
        jkeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(jkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 740, 190, 50));

        jlaporan.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jlaporan.setBorder(null);
        jlaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 490, 160, 30));

        tcari.setBackground(new java.awt.Color(0, 0, 0, 0));
        tcari.setBorder(null);
        tcari.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 230, 20));

        jcari.setBackground(new java.awt.Color(0, 0, 0, 0));
        jcari.setBorder(null);
        jcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcariActionPerformed(evt);
            }
        });
        getContentPane().add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 453, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fitur pembelian sayang.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtambahActionPerformed
        // TODO add your handling code here:

        String idsuplier = tidsuplier.getText();
        String nama_barang = tnamabarang.getText();
        int jumlah = Integer.parseInt(tjumlah.getText());
        String tanggal = ttanggal.getText().isEmpty() ? null : ttanggal.getText();
        double totalharga = Double.parseDouble(ttotalharga.getText());
        String idbarang = tidbarang.getText();
        String username = tusername.getText();

        try {
                String sqlInsert = "INSERT INTO transaksi_beli (id_suplier, nama_barang, jumlah, total_harga, id_barang, username) VALUES (?, ?, ?, ?, ?, ?)";                
                PreparedStatement pstInsert = conn.prepareStatement(sqlInsert);
                pstInsert.setString(1, idsuplier);
                pstInsert.setString(2, nama_barang);
                pstInsert.setInt(3, jumlah);
                pstInsert.setDouble(4, totalharga);
                pstInsert.setString(5, idbarang);
                pstInsert.setString(6, username);
                

                int rowInserted = pstInsert.executeUpdate();
                if (rowInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan");
                    resetForm();
                    getData();
                }
                pstInsert.close();
        }catch (Exception e) {
            Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error saat menambahkan data: " + e.getMessage());
        }
    

    }//GEN-LAST:event_jtambahActionPerformed

    private void tidbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidbarangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tidbarangActionPerformed

    private void jtabeltransaksibeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabeltransaksibeliMouseClicked
        // TODO add your handling code here:
        int selectedRow = jtabeltransaksibeli.getSelectedRow();
if (selectedRow != -1) {
    String idtransaksi = jtabeltransaksibeli.getValueAt(selectedRow, 0).toString();
    String idsuplier = jtabeltransaksibeli.getValueAt(selectedRow, 1).toString();
    String namabarang = jtabeltransaksibeli.getValueAt(selectedRow, 2).toString();
    int jumlah = Integer.parseInt(jtabeltransaksibeli.getValueAt(selectedRow, 3).toString());
    String tanggal = jtabeltransaksibeli.getValueAt(selectedRow, 4).toString(); 
    double totalharga = Double.parseDouble(jtabeltransaksibeli.getValueAt(selectedRow, 5).toString()); // Mengubah dari int ke double
    String idbarang = jtabeltransaksibeli.getValueAt(selectedRow, 6).toString();
    String penjual = jtabeltransaksibeli.getValueAt(selectedRow, 7).toString();
    
    tidtransaksi.setText(idtransaksi);
    tidsuplier.setText(idsuplier);
    tnamabarang.setText(namabarang);
    tjumlah.setText(String.valueOf(jumlah));
    ttanggal.setText(tanggal); 
    ttotalharga.setText(String.valueOf(totalharga)); 
    tidbarang.setText(idbarang);
    tusername.setText(penjual);
}

 
    }//GEN-LAST:event_jtabeltransaksibeliMouseClicked

    private void jubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jubahActionPerformed
   
    int selectedRow = jtabeltransaksibeli.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih tabel yang akan diubah");
        return;
    }

    String idtransaksi = jtabeltransaksibeli.getValueAt(selectedRow, 0).toString();

    String idsuplier = tidsuplier.getText();
    String namabarang = tnamabarang.getText();
    String jumlah = tjumlah.getText();
    String tanggal = ttanggal.getText();
    String totalharga = ttotalharga.getText();
    String idbarang = tidbarang.getText();
    String penjual = tusername.getText();

    if (idsuplier.isEmpty() || namabarang.isEmpty() || jumlah.isEmpty() || tanggal.isEmpty() || totalharga.isEmpty() || idbarang.isEmpty() || penjual.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap lengkapi semua field sebelum mengubah data.");
        return;
    }

    int jumlaha = 0;
    BigDecimal totalhargaa = BigDecimal.ZERO; 
    try {
        jumlaha = Integer.parseInt(jumlah);
        totalhargaa = new BigDecimal(totalharga); 
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah dan Total Harga harus berupa angka yang valid.");
        return;
    }

 
    String sql = "UPDATE transaksi_beli SET jumlah = ?, total_harga = ? WHERE id_transaksi_beli = ?";

    try (PreparedStatement st = conn.prepareStatement(sql)) {
        st.setInt(1, jumlaha);           
        st.setBigDecimal(2, totalhargaa); 
        st.setString(3, idtransaksi);   

       
        int rowsUpdated = st.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
            getData();  
            resetForm();
        } else {
            JOptionPane.showMessageDialog(this, "Data dengan ID tersebut tidak ditemukan atau gagal diperbarui.");
        }
    } catch (SQLException e) {
        Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(Level.SEVERE, null, e);
        JOptionPane.showMessageDialog(this, "Error saat mengubah data: " + e.getMessage());
    }

    }//GEN-LAST:event_jubahActionPerformed

    private void jhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhapusActionPerformed
        // TODO add your handling code here:
        
int selectedRow= jtabeltransaksibeli.getSelectedRow();
            if(selectedRow == 1){
                JOptionPane.showMessageDialog(this,"Pilih tabel yang akan di ubah");
                return;
            }
            String id_barang = jtabeltransaksibeli.getValueAt(selectedRow, 0).toString(); 
    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus item ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            
            String sql = "DELETE FROM transaksi_beli WHERE id_transaksi_beli = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, id_barang);
            int rowsDeleted = st.executeUpdate();
            
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                getData();
                resetForm(); 
                
            }
            
            st.close();
        } catch (Exception e) {
            Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jhapusActionPerformed

    private void jberandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jberandaActionPerformed
        // TODO add your handling code here:
        MenuFitur fitur = new MenuFitur();
        fitur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jberandaActionPerformed

    private void jbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbarangActionPerformed
        // TODO add your handling code here:
        Fitur_Barang barang = new Fitur_Barang();
        barang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbarangActionPerformed

    private void jpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpenjualanActionPerformed
        // TODO add your handling code here:
        Fitur_TransaksiJual penjualan = new Fitur_TransaksiJual();
        penjualan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jpenjualanActionPerformed

    private void jsuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsuplierActionPerformed
        // TODO add your handling code here:
        Fitur_Suplier suplier = new Fitur_Suplier();
        suplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jsuplierActionPerformed

    private void jlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaporanActionPerformed
        // TODO add your handling code here:
        Laporan_Pemasukan laporan = new Laporan_Pemasukan();
        laporan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlaporanActionPerformed

    private void jkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkeluarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.YES_OPTION) {
        System.exit(0); 
    } else {
    }
    }//GEN-LAST:event_jkeluarActionPerformed

    private void jpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpembelianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpembelianActionPerformed

    private void jcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcariActionPerformed
        // TODO add your handling code here:
        String keyword = tcari.getText().trim(); 
    if (!keyword.isEmpty()) {
        searchData(keyword); 
    } else {
        getData(); 
    }
}

private void searchData(String keyword) {
    DefaultTableModel model = (DefaultTableModel) jtabeltransaksibeli.getModel();
    model.setRowCount(0);

    String sql = "SELECT * FROM transaksi_beli WHERE id_transaksi_beli LIKE ? OR nama_barang LIKE ?";
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, "%" + keyword + "%");
        stmt.setString(2, "%" + keyword + "%");

        try (ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
               
                String id_transaksi = rs.getString("id_transaksi_beli");
                String id_suplier = rs.getString("id_suplier");
                String nama_barang = rs.getString("nama_barang");
                String jumlah = rs.getString("jumlah");
                String tanggal = rs.getString("tanggal");
                String harga = rs.getString("total_harga");
                String id_barang = rs.getString("id_barang");
                String username = rs.getString("username");
               
                Object[] rowData = {
                   id_transaksi,id_suplier,nama_barang,jumlah,tanggal,harga,id_barang,username
                };
                model.addRow(rowData);
            }
        }
    } catch (Exception e) {
        Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(Level.SEVERE, "Error saat mencari data", e);
        JOptionPane.showMessageDialog(this, 
            "Error saat mencari data: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jcariActionPerformed

    private void tjumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjumlahActionPerformed
        // TODO add your handling code here:
        try { 
   
    int jumlah = Integer.parseInt(tjumlah.getText());
    int hargaSatuan = 25000; 
    int total = jumlah * hargaSatuan;
    String pembeli = "bayu";

    ttotalharga.setText(String.valueOf(total)); 
    tusername.setText(pembeli);

} catch (NumberFormatException e) { 
    ttotalharga.setText("Input tidak valid");
    tusername.setText("");
}
    }//GEN-LAST:event_tjumlahActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuFitur fitur = new MenuFitur();
        fitur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tnamabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamabarangActionPerformed
        // TODO add your handling code here:
        try {
    // Ambil nama barang dari textField
    String namabarang = tnamabarang.getText();
    String idsuplier = "";
    String idBarang = "";

    // Set nama dan id barang berdasarkan nama barang yang diambil dari textField
    if ("ketan".equalsIgnoreCase(namabarang)) {
        idsuplier = "123456";
        idBarang = "2";
    } else if ("kelapa".equalsIgnoreCase(namabarang)) {
        idsuplier = "654321";
        idBarang = "3";
    }

    // Set teks di textField berdasarkan item yang dipilih
    tidsuplier.setText(idsuplier);
    tidbarang.setText(idBarang);

} catch (NumberFormatException e) {
    tidsuplier.setText("Input tidak valid");
    tidbarang.setText("");
}

    }//GEN-LAST:event_tnamabarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fitur_TransaksiBeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fitur_TransaksiBeli().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbarang;
    private javax.swing.JButton jberanda;
    private javax.swing.JButton jcari;
    private javax.swing.JButton jhapus;
    private javax.swing.JButton jkeluar;
    private javax.swing.JButton jlaporan;
    private javax.swing.JButton jpembelian;
    private javax.swing.JButton jpenjualan;
    private javax.swing.JButton jsuplier;
    private javax.swing.JTable jtabeltransaksibeli;
    private javax.swing.JButton jtambah;
    private javax.swing.JButton jubah;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tidbarang;
    private javax.swing.JTextField tidsuplier;
    private javax.swing.JTextField tidtransaksi;
    private javax.swing.JTextField tjumlah;
    private javax.swing.JTextField tnamabarang;
    private javax.swing.JTextField ttanggal;
    private javax.swing.JTextField ttotalharga;
    private javax.swing.JTextField tusername;
    // End of variables declaration//GEN-END:variables
private void resetForm() {
        tidtransaksi.setText("");
        tidsuplier.setText("");
        tnamabarang.setText("");
        tjumlah.setText("");
        ttanggal.setText("");
        ttotalharga.setText("");
        tidbarang.setText("");
        tusername.setText("");
}
}
