/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyek_michiko_creative;

import koneksi.Koneksi;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author wafiq
 */
public class Fitur_Barang extends javax.swing.JFrame {
private Connection conn;
    /**
     * Creates new form Fitur_Barang
     */
    public Fitur_Barang() {
        initComponents();
        conn = Koneksi.getConnection();
       getData();
    }
     private void getData() {
         DefaultTableModel model = (DefaultTableModel) jtabel.getModel();
         model.setRowCount(0);
         
        try { 
            String sql = "SELECT * FROM barang"; 
            PreparedStatement st = conn.prepareStatement(sql); 
            ResultSet rs = st.executeQuery();
            while (rs.next()) { 
            String id_barang = rs.getString("id_barang"); 
            String nama_barang = rs.getString("nama_barang");
            String jenis = rs.getString("jenis");
            int stock = rs.getInt("stock"); 
            int harga = rs.getInt("harga");
            String penjual = rs.getString("username");
            
            Object[] rowData = {id_barang, nama_barang, jenis, stock, harga, penjual}; 
            model.addRow(rowData); } 
            rs.close(); 
            st.close(); 
        } 
        catch (Exception e){ 
            Logger.getLogger(Fitur_Barang.class.getName()).log(Level.SEVERE, null, e); 
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tid_barang = new javax.swing.JTextField();
        tstock = new javax.swing.JTextField();
        tnama_barang = new javax.swing.JTextField();
        tharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabel = new javax.swing.JTable();
        jedit = new javax.swing.JButton();
        jbfitur = new javax.swing.JButton();
        jbberanda = new javax.swing.JButton();
        jbbarang = new javax.swing.JButton();
        jbpenjualan = new javax.swing.JButton();
        jbpembelian = new javax.swing.JButton();
        jbdatasuplier = new javax.swing.JButton();
        jblaporan = new javax.swing.JButton();
        jbexit = new javax.swing.JButton();
        jtambah = new javax.swing.JButton();
        jhapus = new javax.swing.JButton();
        tjenis = new javax.swing.JTextField();
        tpenjual = new javax.swing.JTextField();
        jcari = new javax.swing.JButton();
        tcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tid_barang.setBackground(new java.awt.Color(0, 0, 0, 0));
        tid_barang.setBorder(null);
        tid_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tid_barangActionPerformed(evt);
            }
        });
        getContentPane().add(tid_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 210, 30));

        tstock.setBackground(new java.awt.Color(0, 0, 0, 0));
        tstock.setBorder(null);
        tstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tstockActionPerformed(evt);
            }
        });
        getContentPane().add(tstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 210, 30));

        tnama_barang.setBackground(new java.awt.Color(0, 0, 0, 0));
        tnama_barang.setBorder(null);
        tnama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnama_barangActionPerformed(evt);
            }
        });
        getContentPane().add(tnama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 210, 30));

        tharga.setBackground(new java.awt.Color(0, 0, 0, 0));
        tharga.setBorder(null);
        tharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thargaActionPerformed(evt);
            }
        });
        getContentPane().add(tharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 220, 30));

        jtabel.setBackground(new java.awt.Color(255, 204, 102));
        jtabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_barang", "nama_barang", "jenis", "stock", "harga", "penjual"
            }
        ));
        jtabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 850, 270));

        jedit.setBackground(new java.awt.Color(255, 204, 0));
        jedit.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jedit.setText("Edit");
        jedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditActionPerformed(evt);
            }
        });
        getContentPane().add(jedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 80, 40));

        jbfitur.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbfitur.setBorder(null);
        jbfitur.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbfitur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbfiturActionPerformed(evt);
            }
        });
        getContentPane().add(jbfitur, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 70, 50));

        jbberanda.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbberanda.setBorder(null);
        jbberanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbberanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbberandaActionPerformed(evt);
            }
        });
        getContentPane().add(jbberanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 110, 30));

        jbbarang.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbbarang.setBorder(null);
        jbbarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbarangActionPerformed(evt);
            }
        });
        getContentPane().add(jbbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 140, 30));

        jbpenjualan.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbpenjualan.setBorder(null);
        jbpenjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpenjualanActionPerformed(evt);
            }
        });
        getContentPane().add(jbpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 250, 180, 30));

        jbpembelian.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbpembelian.setBorder(null);
        jbpembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpembelianActionPerformed(evt);
            }
        });
        getContentPane().add(jbpembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, 180, 30));

        jbdatasuplier.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbdatasuplier.setBorder(null);
        jbdatasuplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbdatasuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdatasuplierActionPerformed(evt);
            }
        });
        getContentPane().add(jbdatasuplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 240, 30));

        jblaporan.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jblaporan.setBorder(null);
        jblaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblaporanActionPerformed(evt);
            }
        });
        getContentPane().add(jblaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, 170, 30));

        jbexit.setBackground(new java.awt.Color(0, 0, 0, 0)
        );
        jbexit.setBorder(null);
        jbexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexitActionPerformed(evt);
            }
        });
        getContentPane().add(jbexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 750, 140, 40));

        jtambah.setBackground(new java.awt.Color(255, 204, 51));
        jtambah.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jtambah.setText("tambah");
        jtambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 100, 40));

        jhapus.setBackground(new java.awt.Color(255, 204, 0));
        jhapus.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jhapus.setText("hapus");
        jhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 450, 100, 40));

        tjenis.setBackground(new java.awt.Color(0, 0, 0, 0));
        tjenis.setBorder(null);
        tjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tjenisActionPerformed(evt);
            }
        });
        getContentPane().add(tjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 210, 30));

        tpenjual.setBackground(new java.awt.Color(0, 0, 0, 0));
        tpenjual.setBorder(null);
        tpenjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpenjualActionPerformed(evt);
            }
        });
        getContentPane().add(tpenjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 220, 30));

        jcari.setBackground(new java.awt.Color(0, 0, 0, 0));
        jcari.setBorder(null);
        jcari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcariActionPerformed(evt);
            }
        });
        getContentPane().add(jcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 40, 40));

        tcari.setBackground(new java.awt.Color(0, 0, 0, 0));
        tcari.setBorder(null);
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });
        getContentPane().add(tcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 230, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fitur barang sayang.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 800));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tid_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tid_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tid_barangActionPerformed

    private void jeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditActionPerformed
    int selectedRow = jtabel.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih tabel yang akan diubah");
        return;
    }

    String id_barang = jtabel.getValueAt(selectedRow, 0).toString();
    
    String nama_barang = tnama_barang.getText();
    String stokText = tstock.getText();
    String hargaText = tharga.getText();
    String jenis = tjenis.getText();
    
    if (nama_barang.isEmpty() || stokText.isEmpty() || hargaText.isEmpty() || jenis.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap lengkapi semua field sebelum mengubah data.");
        return;
    }

    int stock;
    int harga;
    try {
        stock = Integer.parseInt(stokText);
        harga = Integer.parseInt(hargaText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Stok dan Harga harus berupa angka yang valid.");
        return;
    }

    try {
        
        String sql = "UPDATE barang SET nama_barang = ?, jenis = ?, stock = ?, harga = ? WHERE id_barang = ?";
        try (PreparedStatement st = conn.prepareStatement(sql)) {
            st.setString(1, nama_barang);
            st.setString(2, jenis);
            st.setInt(3, stock);
            st.setInt(4, harga);
            st.setString(5, id_barang);

            int rowsUpdated = st.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Diubah");
                getData(); 
                resetForm(); 
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan atau gagal diperbarui.");
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error saat mengubah data: " + e.getMessage());
    }


    }//GEN-LAST:event_jeditActionPerformed

    private void jtabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabelMouseClicked
        // TODO add your handling code here:
        int selectedRow = jtabel.getSelectedRow();
        if (selectedRow != -1) {
            String id_barang = jtabel.getValueAt(selectedRow, 0).toString();
            String nama_barang = jtabel.getValueAt(selectedRow, 1).toString();
            String jenis = jtabel.getValueAt(selectedRow, 2).toString();
            int stock = Integer.parseInt(jtabel.getValueAt(selectedRow, 3).toString());
            int harga = Integer.parseInt(jtabel.getValueAt(selectedRow, 4).toString());
            String penjual = jtabel.getValueAt(selectedRow, 5).toString();
            
            tid_barang.setText(id_barang);
            tnama_barang.setText(nama_barang);
            tjenis.setText(jenis);
            tstock.setText(String.valueOf(stock));
            tharga.setText(String.valueOf(harga));
            tpenjual.setText(penjual);
        }
    }//GEN-LAST:event_jtabelMouseClicked

    private void jblaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblaporanActionPerformed
        // TODO add your handling code here:
        Laporan_Pemasukan laporan = new Laporan_Pemasukan();
        laporan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jblaporanActionPerformed

    private void jbberandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbberandaActionPerformed
        // TODO add your handling code here:
         MenuFitur fitur = new MenuFitur();
        fitur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbberandaActionPerformed

    private void jbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexitActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (response == JOptionPane.YES_OPTION) {
        System.exit(0); 
    } else {
    }
    }//GEN-LAST:event_jbexitActionPerformed

    private void jtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtambahActionPerformed
        // TODO add your handling code here:
    String id_barang = tid_barang.getText();
    String nama_barang = tnama_barang.getText();
    String jenis = tjenis.getText();
    int stokText = Integer.parseInt(tstock.getText());
    int hargaText = Integer.parseInt(tharga.getText());
    String penjual = tpenjual.getText();

    try {
        String checkSql = "SELECT stock FROM barang WHERE id_barang = ? AND nama_barang = ?";
        PreparedStatement checkSt = conn.prepareStatement(checkSql);
        checkSt.setString(1, id_barang);
        checkSt.setString(2, nama_barang);

        ResultSet rs = checkSt.executeQuery();

        if (rs.next()) {
            int currentStock = rs.getInt("stock");
            int newStock = currentStock + stokText;
            String updateSql = "UPDATE barang SET stock = ? WHERE id_barang = ? AND nama_barang = ?";
            PreparedStatement updateSt = conn.prepareStatement(updateSql);
            updateSt.setInt(1, newStock);
            updateSt.setString(2, id_barang);
            updateSt.setString(3, nama_barang);

            int rowUpdated = updateSt.executeUpdate();
            if (rowUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Stok berhasil diperbarui.");
                resetForm();
                getData();
            }

            updateSt.close();
        } else {
            String insertSql = "INSERT INTO barang (id_barang, nama_barang, jenis, stock, harga, username) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement insertSt = conn.prepareStatement(insertSql);
            insertSt.setString(1, id_barang);
            insertSt.setString(2, nama_barang);
            insertSt.setString(3, jenis);
            insertSt.setInt(4, stokText);
            insertSt.setInt(5, hargaText);
            insertSt.setString(6, penjual);

            int rowInserted = insertSt.executeUpdate();
            if (rowInserted > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan.");
                resetForm();
                getData();
            }

            insertSt.close();
        }

        rs.close();
        checkSt.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saat menambahkan atau memperbarui data: " + e.getMessage());
    }


    }//GEN-LAST:event_jtambahActionPerformed

    private void jhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhapusActionPerformed
        // TODO add your handling code here:
        int selectedRow= jtabel.getSelectedRow();
            if(selectedRow == -1){
                JOptionPane.showMessageDialog(this,"Pilih tabel yang akan di ubah");
                return;
            }
            String id_barang = jtabel.getValueAt(selectedRow, 0).toString(); 
    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus item ini?", 
            "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            
            String sql = "DELETE FROM barang WHERE id_barang = ?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, id_barang);
            int rowsDeleted = st.executeUpdate();
            
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                getData();
                resetForm(); 
                
            }
            
            st.close();
        } catch (Exception e) {
            Logger.getLogger(Fitur_Barang.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jhapusActionPerformed

    private void jbdatasuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdatasuplierActionPerformed
        // TODO add your handling code here:
         Fitur_Suplier suplier = new Fitur_Suplier();
        suplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbdatasuplierActionPerformed

    private void tjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tjenisActionPerformed

    private void thargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thargaActionPerformed

    private void tpenjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpenjualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpenjualActionPerformed

    private void jcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcariActionPerformed
        // TODO add your handling code here:
        String keyword = tcari.getText().trim();
    if (!keyword.isEmpty()) {
        searchData(keyword); 
    } else {
        getData(); 
    }
}

private void searchData(String keyword) {
    DefaultTableModel model = (DefaultTableModel) jtabel.getModel();
    model.setRowCount(0);
    String sql = "SELECT * FROM barang WHERE id_barang LIKE ? OR nama_barang LIKE ?";
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, "%" + keyword + "%");
        stmt.setString(2, "%" + keyword + "%");

        try (ResultSet rs = stmt.executeQuery()) {
            while (rs.next()) {
                String id_barang = rs.getString("id_barang");
                String nama_barang = rs.getString("nama_barang");
                String jenis = rs.getString("jenis");
                String stok = rs.getString("stock");
                String harga = rs.getString("harga");
                String username = rs.getString("username");
               
                Object[] rowData = {
                   id_barang,nama_barang,jenis,stok,harga,username
                };
                model.addRow(rowData);
            }
        }
    } catch (Exception e) {
        Logger.getLogger(Fitur_Barang.class.getName()).log(Level.SEVERE, "Error saat mencari data", e);
        JOptionPane.showMessageDialog(this, 
            "Error saat mencari data: " + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jcariActionPerformed

    private void jbpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpenjualanActionPerformed
        // TODO add your handling code here:
        Fitur_TransaksiJual suplier = new Fitur_TransaksiJual();
        suplier.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbpenjualanActionPerformed

    private void jbbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbbarangActionPerformed

    private void jbpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpembelianActionPerformed
        // TODO add your handling code here:
        Fitur_TransaksiBeli pembelian = new Fitur_TransaksiBeli();
        pembelian.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbpembelianActionPerformed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void jbfiturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbfiturActionPerformed
        // TODO add your handling code here:
        MenuFitur fitur = new MenuFitur();
        fitur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbfiturActionPerformed

    private void tnama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnama_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnama_barangActionPerformed

    private void tstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tstockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fitur_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fitur_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fitur_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fitur_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fitur_Barang().setVisible(true);
            }  
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbbarang;
    private javax.swing.JButton jbberanda;
    private javax.swing.JButton jbdatasuplier;
    private javax.swing.JButton jbexit;
    private javax.swing.JButton jbfitur;
    private javax.swing.JButton jblaporan;
    private javax.swing.JButton jbpembelian;
    private javax.swing.JButton jbpenjualan;
    private javax.swing.JButton jcari;
    private javax.swing.JButton jedit;
    private javax.swing.JButton jhapus;
    private javax.swing.JTable jtabel;
    private javax.swing.JButton jtambah;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tid_barang;
    private javax.swing.JTextField tjenis;
    private javax.swing.JTextField tnama_barang;
    private javax.swing.JTextField tpenjual;
    private javax.swing.JTextField tstock;
    // End of variables declaration//GEN-END:variables
private void resetForm() {
        tid_barang.setText("");
        tnama_barang.setText("");
        tjenis.setText("");
        tstock.setText("");
        tharga.setText("");
        tpenjual.setText("");
        
}}

